[package]
name = "dd"
version = "0.1.0"
edition = "2021"
authors = ["Georgiy Komarov <jubnzv@gmail.com>"]

[dependencies]
env_logger = "0.9.*"
clap = "2.34.*"
log = "0.4.*"
tree-sitter = "0.20.*"

[build-dependencies]
cc="*"
